### ISSUE TITLE
Problema al generar reporte de Factura Electrónica

### ISSUE THREAD

**Issue by ceciliasp** [ceciliasp/Coprinf-Tryton#1]
Al querer generar el reporte de la Factura (ya confirmada y con CAE) aparece el siguiente error:
Traceback (most recent call last):
File "/trytond/protocols/jsonrpc.py", line 150, in _marshaled_dispatch
response['result'] = dispatch_method(method, params)
File "/trytond/protocols/jsonrpc.py", line 179, in _dispatch
res = dispatch(args)
File "/trytond/protocols/dispatcher.py", line 161, in dispatch
result = rpc.result(meth(c_args, **c_kwargs))
File "/trytond/modules/account_invoice/invoice.py", line 2450, in execute
res = super(InvoiceReport, cls).execute(ids, data)
File "/trytond/report/report.py", line 144, in execute
type, data = cls.parse(action_report, records, data, {})
File "/trytond/modules/account_invoice_ar/invoice.py", line 706, in parse
localcontext=localcontext)
File "/trytond/modules/account_invoice/invoice.py", line 2479, in parse
localcontext)
File "/trytond/report/report.py", line 300, in parse
data = cls.unoconv(data, report.template_extension, output_format)
File "/trytond/report/report.py", line 320, in unoconv
raise Exception(stderrdata)
Exception: None

La versión de invoice_ar es la 3.4.2. con la base actualizada.
Unoconv instalado. Python-UNO ya no está disponible en Python 2.7.

En acciones / informe, la extensión que aparece es Open Office Text Document. Al querer blanquearlo aparece el error "No está autorizado a cambiar este registro. Este registro pertenece a la configuración base". (ver prtscreen)

**Comment by ceciliasp** [comment]
Si no tenés necesidad de convertir a pdf la salida del reporte, no se debería estar usando unoconv. 

El campo extensión del reporte, debería estar en blanco como bien describís en la incidencia. Podes intentar blanquear el campo desde psql de Postgres (seguramente va a volver a tener un valor en cuanto ejecutes un update del módulo account_invoice con Tryton, porque el reporte está definido en un archivo xml del módulo)

Primero, tenés que averiguar el id del registro del reporte. Desde el formulario del reporte, hacés click en el ícono de herramientas y seleccionas, ver registros.

Después desde la consola ejecutás estos comandos:

psql -d tu_base_de_datos
update ir_action_report set extension = null where id = id_reporte;
